server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb?timezone=Asia/Kolkata
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
